"""add URL click analytics

Revision ID: 26ea792410cf
Revises: af21a4c9dc2d
Create Date: 2026-09-22 15:22:00.625992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ea792410cf'
down_revision: Union[str, Sequence[str], None] = 'af21a4c9dc2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_clicks_clicked_at'), 'url_clicks', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_url_clicks_id'), 'url_clicks', ['id'], unique=False)
    op.create_index(op.f('ix_url_clicks_url_id'), 'url_clicks', ['url_id'], unique=False)
    op.create_index('ix_url_clicks_url_id_clicked_at', 'url_clicks', ['url_id', 'clicked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_url_clicks_url_id_clicked_at', table_name='url_clicks')
    op.drop_index(op.f('ix_url_clicks_url_id'), table_name='url_clicks')
    op.drop_index(op.f('ix_url_clicks_id'), table_name='url_clicks')
    op.drop_index(op.f('ix_url_clicks_clicked_at'), table_name='url_clicks')
    op.drop_table('url_clicks')
    # ### end Alembic commands ###
